export const GET_BREAKINGNEWS = 'GET_BREAKINGNEWS';
export const GET_EDITORSPICKS = 'GET_EDITORSPICKS';
export const GET_NEWSWATCH = 'GET_NEWSWATCH';
export const GET_HEALTHSECTION = 'GET_HEALTHSECTION';